// Turns a rendered sheet's layout (out/placard-<variant>.layout.json, written
// by build.mjs) into Figma Plugin API code that rebuilds the sheet as one
// frame: 72 units to the inch, so an 11 × 17 in sheet is a 792 × 1224 frame
// and a PDF exported from Figma comes out at the print size. Text is live
// text in the site's fonts (Courier Prime, Geist, both on Google Fonts and
// so in Figma), the mark and the QR are vectors, and the shot is a rectangle
// that the upload step fills with the PNG.
//
//   node figma.mjs a-dots > out/figma-a-dots.js
//
// The code is meant for the Figma MCP `use_figma` tool (or a plugin's
// console). PAGE_ID and AT say where the frame lands; the frame's own name
// carries the variant. Returns the ids of everything it made, the shot's
// rectangle id first, for the image upload that follows.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const variant = process.argv[2] || 'a-dots'
const PAGE_ID = process.env.PAGE_ID || '1239:25709'
const AT = { x: Number(process.env.AT_X || 22000), y: Number(process.env.AT_Y || -4000) }
const L = JSON.parse(fs.readFileSync(path.join(HERE, 'out', `placard-${variant}.layout.json`), 'utf8'))
const IN = 72

const STYLE = { 'Courier Prime': { 400: 'Regular', 700: 'Bold' }, Geist: { 300: 'Light', 400: 'Regular', 500: 'Medium', 600: 'SemiBold' }, 'Playfair Display': { 400: 'Regular', 500: 'Medium' } }
const rgb = (css) => { const m = css.match(/[\d.]+/g).map(Number); return { r: m[0] / 255, g: m[1] / 255, b: m[2] / 255 } }
const hex = (h) => ({ r: parseInt(h.slice(1, 3), 16) / 255, g: parseInt(h.slice(3, 5), 16) / 255, b: parseInt(h.slice(5, 7), 16) / 255 })
const r3 = (n) => Math.round(n * 1000) / 1000

const fonts = new Map()
const texts = []
for (const n of L.nodes) {
  if (n.type !== 'text') continue
  // The nearest style the family has: Courier Prime ships 400 and 700 only,
  // so a lighter weight it inherited from the body maps to Regular.
  const styles = STYLE[n.family]
  if (!styles) throw new Error(`no Figma styles for ${n.family}`)
  const weights = Object.keys(styles).map(Number)
  const nearest = weights.reduce((a, b) => (Math.abs(b - n.weight) < Math.abs(a - n.weight) ? b : a))
  const style = styles[nearest]
  fonts.set(`${n.family}/${style}`, { family: n.family, style })
  // A box that held one line in the browser is auto-width in Figma, so a
  // rounding difference in the font's advance cannot wrap it; a paragraph
  // keeps its width (plus a point of slack) and grows in height.
  const lines = Math.max(1, Math.round(n.h / ((n.sizePt / 72) * n.lineHeight)))
  texts.push({
    name: n.text.split('\n')[0].slice(0, 40), text: n.text, family: n.family, style, lines,
    x: r3(n.x * IN), y: r3(n.y * IN), w: r3(n.w * IN), h: r3(n.h * IN),
    size: r3(n.sizePt), lh: r3(n.lineHeight * 100), ls: r3(n.letterSpacing * 100),
    upper: n.transform === 'uppercase', align: n.align === 'right' ? 'RIGHT' : n.align === 'center' ? 'CENTER' : 'LEFT',
    color: rgb(n.color),
  })
}
const images = L.nodes.filter((n) => n.type === 'image').map((n) => ({ name: n.name, x: r3(n.x * IN), y: r3(n.y * IN), w: r3(n.w * IN), h: r3(n.h * IN), framed: n.framed }))
const svgs = L.nodes.filter((n) => n.type === 'svg').map((n) => ({ name: n.name, x: r3(n.x * IN), y: r3(n.y * IN), w: r3(n.w * IN), h: r3(n.h * IN), svg: n.svg }))

const code = `// A Decade of Rain · NACIS 2026 placard ${variant} · generated by poster/nacis-2026/figma.mjs
const page = await figma.getNodeByIdAsync(${JSON.stringify(PAGE_ID)})
await figma.setCurrentPageAsync(page)
const FONTS = ${JSON.stringify([...fonts.values()])}
for (const f of FONTS) await figma.loadFontAsync(f)

// A rerun replaces the frame it made before, so the page never holds two.
const NAME = ${JSON.stringify(`NACIS 2026 placard · ${variant} · 11×17 in (72/in)`)}
const removed = []
for (const n of page.children) if (n.name === NAME) { removed.push(n.id); n.remove() }

const frame = figma.createFrame()
frame.name = NAME
frame.resize(${L.widthIn * IN}, ${L.heightIn * IN})
frame.x = ${AT.x}; frame.y = ${AT.y}
frame.fills = [{ type: 'SOLID', color: ${JSON.stringify(hex(L.background))} }]
frame.clipsContent = true
page.appendChild(frame)

const made = { frameId: frame.id, replaced: removed, shotIds: [], textIds: [], vectorIds: [] }

const IMAGES = ${JSON.stringify(images)}
for (const s of IMAGES) {
  const r = figma.createRectangle()
  r.name = 'shot · ' + s.name
  r.resize(s.w, s.h)
  r.fills = [{ type: 'SOLID', color: { r: 0.933, g: 0.941, b: 0.918 } }]
  if (s.framed) { r.strokes = [{ type: 'SOLID', color: ${JSON.stringify(hex('#dfe3d9'))} }]; r.strokeWeight = 1; r.strokeAlign = 'INSIDE' }
  frame.appendChild(r)
  r.x = s.x; r.y = s.y
  made.shotIds.push(r.id)
}

const SVGS = ${JSON.stringify(svgs)}
for (const s of SVGS) {
  const v = figma.createNodeFromSvg(s.svg)
  v.name = s.name === 'qr' ? 'QR · https://rain.sizheng.me/' : 'mark'
  frame.appendChild(v)
  v.resize(s.w, s.h)
  v.x = s.x; v.y = s.y
  made.vectorIds.push(v.id)
}

const TEXTS = ${JSON.stringify(texts)}
for (const t of TEXTS) {
  const n = figma.createText()
  n.fontName = { family: t.family, style: t.style }
  n.characters = t.text
  n.name = t.name
  n.fontSize = t.size
  n.lineHeight = { unit: 'PERCENT', value: t.lh }
  n.letterSpacing = { unit: 'PERCENT', value: t.ls }
  n.textCase = t.upper ? 'UPPER' : 'ORIGINAL'
  n.textAlignHorizontal = t.align
  n.fills = [{ type: 'SOLID', color: t.color }]
  if (t.lines === 1) {
    n.textAutoResize = 'WIDTH_AND_HEIGHT'
  } else {
    n.textAutoResize = 'HEIGHT'
    n.resize(t.w + 1, t.h)
  }
  frame.appendChild(n)
  // Right-aligned text keeps its right edge where the browser put it.
  n.x = t.align === 'RIGHT' ? t.x + t.w - n.width : t.align === 'CENTER' ? t.x + (t.w - n.width) / 2 : t.x
  n.y = t.y
  made.textIds.push(n.id)
}
return { ...made, frame: { x: frame.x, y: frame.y, w: frame.width, h: frame.height, children: frame.children.length } }
`
process.stdout.write(code)
console.error(`${texts.length} texts, ${images.length} shots, ${svgs.length} vectors, ${code.length} chars of code`)
